name: Manual .NET Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ⚠️ Start build process
      run: echo "Build process has started..."

    - name: Show runtime context
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Repository: ${{ github.repository }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Triggered By: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        echo "Run number: ${{ github.run_number }}"
        echo "Branch: ${{ github.ref }}"
